# Generated by Django 3.2.16 on 2022-10-24 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RunName',
            fields=[
                ('runs', models.CharField(choices=[('Early_Grind', 'Early_Grind'), ('Recovery_Run', 'Recovery_Run'), ('Twilight_Hustle', 'Twilight_Hustle')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Fully_Booked', 'Fully_Booked'), ('Availble', 'Availble')], default='Available', max_length=15)),
                ('seats', models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('requested_date', models.DateField()),
                ('bookingtatus', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('p', 'Pending')], default='p', max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='booking.customer')),
                ('run_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='booking.runname')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
